Title = 'Ndtp Proxy'
Localport = 9000
Index_head = 0
Sql_active = false
Levellog = 1
PortControl=8081

[Sql_param]
Driver = 'PG'
Host = 'localhost'
Port = 5432
User = 'nsmsave'
Password = ''
Dbname = 'nsm'
Lenbuf = 900
Ins_value ='temp_proxy(event, time_session, Id_session, str_json)'

[[Server]]
Name = '192.168.194.242'
Port = 9101
Active = true

##[[Server]]
##Name = 'localhost'
##Port = 9002
##Active = false
